<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Liquidation · ProcureMS</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>tailwind.config={theme:{extend:{colors:{surface:'#faf8ff','surface-low':'#f4f3fa','surface-container':'#eeedf4','surface-high':'#e9e7ef',primary:'#00236f','primary-container':'#1e3a8a','on-surface':'#1a1b21','on-surface-variant':'#444651',secondary:'#006c4a','outline-variant':'#c5c5d3',error:'#ba1a1a'},fontFamily:{inter:['Inter','sans-serif']}}}};</script>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,400,0,0" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="bg-surface font-inter text-on-surface antialiased">
@php
    $isMasterUser = $isMasterUser ?? auth()->user()?->role === 'master_user';
    $statusLabels = ['draft' => 'Draft', 'for_review' => 'For Review', 'pending_documents' => 'Pending Documents', 'approved' => 'Approved', 'returned' => 'Returned'];
    $statusTones = ['draft' => 'on-surface-variant', 'for_review' => 'error', 'pending_documents' => 'primary', 'approved' => 'secondary', 'returned' => 'error'];
@endphp
<aside class="fixed inset-y-0 left-0 z-50 hidden w-72 flex-col bg-primary px-4 py-6 text-white md:flex"><div class="mb-8 flex items-center gap-3 px-2"><div class="flex h-8 w-8 items-center justify-center rounded bg-secondary"><span class="material-symbols-outlined text-[20px]">school</span></div><span class="text-xl font-semibold">ProcureMS</span></div><nav class="flex-1 space-y-1" aria-label="Main navigation">
    @php
        $navigation=[['icon'=>'dashboard','label'=>'Dashboard','route'=>'home'],['icon'=>'shopping_cart','label'=>'Procurement','route'=>'procurement'],['icon'=>'receipt_long','label'=>'Liquidation','route'=>'liquidation','active'=>true],['icon'=>'folder','label'=>'Google Drive','route'=>'google-drive'],['icon'=>'bar_chart','label'=>'Reports','route'=>'reports']];
        if ($isMasterUser) { $navigation[]=['icon'=>'group','label'=>'User Management','route'=>'user-management']; $navigation[]=['icon'=>'card_membership','label'=>'Subscriptions','route'=>'subscriptions']; }
        $navigation[]=['icon'=>'settings','label'=>'School Settings','route'=>'school-settings'];
    @endphp
    @foreach($navigation as $item)<a href="{{ route($item['route']) }}" class="flex items-center rounded px-3 py-2.5 text-sm {{ ($item['active'] ?? false) ? 'bg-primary-container font-semibold text-white' : 'text-white/80 hover:bg-primary-container hover:text-white' }}"><span class="material-symbols-outlined mr-3 text-[20px]">{{ $item['icon'] }}</span>{{ $item['label'] }}</a>@if(($item['label'] ?? '') === 'Dashboard')<details class="group"><summary class="flex cursor-pointer list-none items-center rounded px-3 py-2.5 text-sm text-white/80 hover:bg-primary-container hover:text-white"><span class="material-symbols-outlined mr-3 text-[20px]">account_balance_wallet</span><span class="flex-1">Finance</span><span class="material-symbols-outlined text-[18px] transition-transform group-open:rotate-180">expand_more</span></summary><div class="mt-1 space-y-1"><a href="{{ route('liquidation', ['finance' => 'budget']) }}" class="ml-8 flex items-center rounded px-3 py-2 text-sm text-white/75 hover:bg-primary-container hover:text-white"><span class="material-symbols-outlined mr-2 text-[17px]">account_balance</span>Budget</a><a href="{{ route('liquidation', ['finance' => 'accounting']) }}" class="ml-8 flex items-center rounded px-3 py-2 text-sm text-white/75 hover:bg-primary-container hover:text-white"><span class="material-symbols-outlined mr-2 text-[17px]">request_quote</span>Accounting</a><a href="{{ route('liquidation', ['finance' => 'cash']) }}" class="ml-8 flex items-center rounded px-3 py-2 text-sm text-white/75 hover:bg-primary-container hover:text-white"><span class="material-symbols-outlined mr-2 text-[17px]">payments</span>Cash</a></div></details>@endif @endforeach
</nav><div class="border-t border-white/15 pt-4 text-xs text-white/60"><p>Multi-School Procurement System</p><p class="mt-1">v1.0 · All systems operational</p></div></aside>

<div class="md:pl-72"><header class="fixed left-0 right-0 top-0 z-40 flex h-16 items-center justify-between border-b border-outline-variant/30 bg-surface/95 px-4 backdrop-blur md:left-72 md:px-6"><div class="flex items-center gap-3"><button class="rounded p-2 text-on-surface-variant md:hidden" aria-label="Open navigation"><span class="material-symbols-outlined">menu</span></button><span class="text-sm font-semibold text-on-surface-variant">Liquidation Workspace</span></div><div class="flex items-center gap-4"><button class="relative rounded p-1 text-on-surface-variant" aria-label="Notifications"><span class="material-symbols-outlined text-[21px]">notifications</span>@if(($metrics['forReview'] ?? 0) || ($metrics['pendingDocuments'] ?? 0))<span class="absolute right-0 top-0 h-2 w-2 rounded-full bg-error"></span>@endif</button><button id="open-user-menu" type="button" class="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-white hover:bg-primary-container" aria-label="User menu"><span class="material-symbols-outlined text-[18px]">person</span></button></div></header>
<main class="min-h-screen bg-surface px-4 pb-16 pt-24 md:px-6 lg:px-8"><div class="mx-auto max-w-[1600px]">
    <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div class="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-on-surface-variant"><span class="material-symbols-outlined text-[16px]">receipt_long</span><span class="font-semibold text-primary">Liquidation</span></div><h1 class="text-[28px] font-semibold leading-9 tracking-tight">Liquidation</h1><p class="mt-1 text-[15px] leading-6 text-on-surface-variant">Start with ORS, then track budget review, cash release, documents, and final liquidation status.</p></div><button type="button" id="open-liquidation-modal" class="flex items-center justify-center gap-2 rounded bg-primary px-4 py-2.5 text-xs font-semibold text-white hover:bg-primary-container"><span class="material-symbols-outlined text-[18px]">add</span>New ORS Entry</button></div>
    @if(session('success'))<div class="mb-5 rounded border border-secondary/30 bg-secondary/5 px-4 py-3 text-sm text-secondary">{{ session('success') }}</div>@endif
    @if($errors->any())<div class="mb-5 rounded border border-error/30 bg-error/5 px-4 py-3 text-sm text-error">Please review the liquidation details and try again.</div>@endif

    @php $metricCards=[['label'=>'Total Liquidations','value'=>$metrics['total'] ?? 0,'note'=>'₱'.number_format((float)($metrics['totalAmount'] ?? 0),2).' recorded','icon'=>'receipt_long','tone'=>'primary'],['label'=>'For Review','value'=>$metrics['forReview'] ?? 0,'note'=>'Requires attention','icon'=>'fact_check','tone'=>'error'],['label'=>'Pending Documents','value'=>$metrics['pendingDocuments'] ?? 0,'note'=>'Missing attachments','icon'=>'upload_file','tone'=>'primary'],['label'=>'Approved This Month','value'=>$metrics['approvedThisMonth'] ?? 0,'note'=>'Processed this month','icon'=>'verified','tone'=>'secondary']]; @endphp
    <div class="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($metricCards as $metric)<article class="flex items-center justify-between rounded border border-outline-variant/30 bg-white p-5"><div><p class="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">{{ $metric['label'] }}</p><p class="mt-3 text-3xl font-semibold tabular-nums {{ $metric['tone']==='error' ? 'text-error' : '' }}">{{ $metric['value'] }}</p><p class="mt-1 text-xs font-medium text-{{ $metric['tone'] }}">{{ $metric['note'] }}</p></div><div class="flex h-10 w-10 items-center justify-center rounded bg-{{ $metric['tone'] }}/10 text-{{ $metric['tone'] }}"><span class="material-symbols-outlined">{{ $metric['icon'] }}</span></div></article>@endforeach</div>

    <section class="overflow-hidden rounded border border-outline-variant/30 bg-white"><div class="flex flex-col justify-between gap-4 border-b border-outline-variant/30 p-5 lg:flex-row lg:items-center"><div><h2 class="text-lg font-semibold">Liquidation Records</h2><p class="mt-1 text-xs text-on-surface-variant">Validate ORS entries, budget processing, cash release, and liquidation documents.</p></div><form method="GET" action="{{ route('liquidation') }}" class="flex flex-wrap gap-2"><div class="relative"><span class="material-symbols-outlined absolute left-3 top-2.5 text-[18px] text-on-surface-variant">search</span><input name="search" value="{{ $search }}" class="w-full rounded border border-outline-variant/50 bg-surface-low py-2 pl-9 pr-3 text-xs outline-none focus:border-primary sm:w-56" placeholder="Search ORS, purpose..." type="search"></div>@if($isMasterUser)<select name="school_id" class="rounded border border-outline-variant/50 bg-surface-low px-3 py-2 text-xs outline-none"><option value="">All schools</option>@foreach($schools as $school)<option value="{{ $school->id }}" @selected((string)$selectedSchoolId === (string)$school->id)>{{ $school->name }}</option>@endforeach</select>@endif<select name="status" class="rounded border border-outline-variant/50 bg-surface-low px-3 py-2 text-xs outline-none">@foreach(['all'=>'All Statuses'] + $statusLabels as $value => $label)<option value="{{ $value }}" @selected($selectedStatus === $value)>{{ $label }}</option>@endforeach</select><button class="rounded bg-primary px-4 py-2 text-xs font-semibold text-white">Filter</button></form></div>
        <div class="overflow-x-auto"><table class="w-full min-w-[1000px] border-collapse text-left"><thead class="bg-surface-low text-xs uppercase tracking-wider text-on-surface-variant"><tr class="border-b border-outline-variant/30"><th class="px-5 py-3 font-semibold">ORS / Transaction</th><th class="px-5 py-3 font-semibold">School</th><th class="px-5 py-3 font-semibold">Submitted By</th><th class="px-5 py-3 font-semibold">Amount</th><th class="px-5 py-3 font-semibold">Status</th><th class="px-5 py-3 font-semibold">Submitted</th><th class="px-5 py-3 text-right font-semibold">Actions</th></tr></thead><tbody class="divide-y divide-outline-variant/20 text-[13px]">
        @forelse($liquidations as $liquidation)
            @php $tone = $statusTones[$liquidation->status] ?? 'primary'; @endphp
            <tr class="hover:bg-surface-low/60"><td class="px-5 py-3.5"><div class="font-semibold text-primary">{{ $liquidation->ors_number ?: 'ORS not set' }}</div><div class="mt-0.5 text-[11px] font-semibold text-on-surface-variant">Liquidation: {{ $liquidation->report_number }}</div><div class="mt-1 text-xs text-on-surface-variant">{{ $liquidation->purpose ?: ($liquidation->procurementRequest?->title ?? 'General liquidation') }}</div>@if($liquidation->procurementRequest)<div class="mt-0.5 text-[11px] text-on-surface-variant">Linked PR: {{ $liquidation->procurementRequest->request_number }}</div>@endif</td><td class="px-5 py-3.5 font-medium">{{ $liquidation->school?->name ?? 'School not found' }}</td><td class="px-5 py-3.5 text-on-surface-variant">{{ $liquidation->submitter?->name ?? 'System' }}</td><td class="px-5 py-3.5 font-semibold tabular-nums">₱{{ number_format((float)$liquidation->amount, 2) }}</td><td class="px-5 py-3.5"><span class="inline-flex rounded-full bg-{{ $tone }}/10 px-2 py-1 text-xs font-semibold text-{{ $tone }}">{{ $statusLabels[$liquidation->status] ?? Str::headline($liquidation->status) }}</span></td><td class="px-5 py-3.5 text-on-surface-variant">{{ $liquidation->submitted_at?->format('M d, Y') ?? $liquidation->created_at?->format('M d, Y') }}</td><td class="px-5 py-3.5 text-right"><div class="flex justify-end gap-1">@if($isMasterUser)<form method="POST" action="{{ route('liquidation.status', $liquidation) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="approved"><button class="rounded px-2 py-1 text-xs font-semibold text-secondary hover:bg-secondary hover:text-white">Approve</button></form><form method="POST" action="{{ route('liquidation.status', $liquidation) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="pending_documents"><button class="rounded px-2 py-1 text-xs font-semibold text-primary hover:bg-primary hover:text-white">Docs</button></form><form method="POST" action="{{ route('liquidation.status', $liquidation) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="returned"><button class="rounded px-2 py-1 text-xs font-semibold text-error hover:bg-error hover:text-white">Return</button></form>@else<span class="text-xs text-on-surface-variant">Submitted</span>@endif</div></td></tr>
        @empty
            <tr><td colspan="7" class="px-5 py-10 text-center text-sm text-on-surface-variant">No liquidation records found. Use New ORS Entry to submit the first record.</td></tr>
        @endforelse
        </tbody></table></div><div class="flex flex-col justify-between gap-3 border-t border-outline-variant/20 bg-surface-low px-5 py-3 text-xs text-on-surface-variant sm:flex-row sm:items-center"><span>Showing {{ $liquidations->count() }} liquidation {{ Str::plural('record', $liquidations->count()) }}</span><span>Filtered from live records</span></div>
    </section>

    <div class="mt-8 grid grid-cols-1 gap-4 lg:grid-cols-2"><section class="rounded border border-outline-variant/30 bg-white p-5"><div class="mb-5 flex items-center justify-between"><div><h3 class="text-lg font-semibold">Liquidation Workflow</h3><p class="mt-1 text-xs text-on-surface-variant">Liquidation records by current review stage.</p></div><span class="material-symbols-outlined text-on-surface-variant">account_tree</span></div><div class="space-y-4">@foreach($statusLabels as $statusKey => $label)@php $count=$statusCounts[$statusKey] ?? 0; $percent=max(4, ($metrics['total'] ?? 0) ? round(($count / max(1,$metrics['total'])) * 100) : 4); $tone=$statusTones[$statusKey] ?? 'primary'; @endphp<div><div class="mb-1 flex justify-between text-xs"><span>{{ $label }}</span><span class="font-semibold">{{ $count }} records</span></div><div class="h-2 rounded-full bg-surface-container"><div class="h-full rounded-full bg-{{ $tone }}" style="width: {{ $percent }}%"></div></div></div>@endforeach</div></section><section class="rounded border border-outline-variant/30 bg-white p-5"><div class="mb-5 flex items-center justify-between"><div><h3 class="text-lg font-semibold">Review Queue</h3><p class="mt-1 text-xs text-on-surface-variant">Items needing your attention.</p></div><span class="material-symbols-outlined text-on-surface-variant">fact_check</span></div><div class="space-y-2"><div class="flex items-center justify-between rounded bg-error/5 p-3"><div class="flex items-center gap-3"><span class="material-symbols-outlined text-error">priority_high</span><div><p class="text-xs font-semibold">{{ $metrics['forReview'] ?? 0 }} records for review</p><p class="mt-1 text-xs text-on-surface-variant">Check ORS details, receipts, and supporting documents</p></div></div><a href="{{ route('liquidation', ['status'=>'for_review']) }}" class="text-xs font-semibold text-primary hover:underline">Review</a></div><div class="flex items-center justify-between rounded bg-primary/5 p-3"><div class="flex items-center gap-3"><span class="material-symbols-outlined text-primary">upload_file</span><div><p class="text-xs font-semibold">{{ $metrics['pendingDocuments'] ?? 0 }} missing documents</p><p class="mt-1 text-xs text-on-surface-variant">Follow up with school custodians</p></div></div><a href="{{ route('liquidation', ['status'=>'pending_documents']) }}" class="text-xs font-semibold text-primary hover:underline">View</a></div><div class="flex items-center justify-between rounded bg-secondary/5 p-3"><div class="flex items-center gap-3"><span class="material-symbols-outlined text-secondary">task_alt</span><div><p class="text-xs font-semibold">{{ $metrics['approvedThisMonth'] ?? 0 }} approved this month</p><p class="mt-1 text-xs text-on-surface-variant">Approved records are timestamped automatically</p></div></div><a href="{{ route('liquidation', ['status'=>'approved']) }}" class="text-xs font-semibold text-primary hover:underline">Open</a></div></div></section></div>
</div></main></div>

<div id="liquidation-modal" class="fixed inset-0 z-[100] hidden items-center justify-center bg-black/50 p-4" role="dialog" aria-modal="true"><div class="w-full max-w-2xl rounded bg-white shadow-2xl"><div class="flex items-center justify-between border-b border-outline-variant/30 px-6 py-4"><div><h2 class="text-lg font-semibold">New ORS Entry</h2><p class="mt-1 text-xs text-on-surface-variant">Create the ORS record before budget review and cash processing.</p></div><button type="button" data-close-liquidation-modal class="rounded p-2 hover:bg-primary hover:text-white"><span class="material-symbols-outlined">close</span></button></div>
    <form method="POST" action="{{ route('liquidation.store') }}" class="grid grid-cols-1 gap-4 p-6 md:grid-cols-2">@csrf
        <label class="text-xs font-semibold text-on-surface-variant">ORS Number <span class="text-error">*</span><input name="ors_number" required value="{{ old('ors_number') }}" placeholder="e.g. ORS-2026-0001" class="mt-2 w-full rounded border border-outline-variant/50 bg-surface-low px-3 py-2.5 text-sm font-normal outline-none focus:border-primary"></label>
        @if($isMasterUser)<label class="text-xs font-semibold text-on-surface-variant">School <span class="text-error">*</span><select name="school_id" required class="mt-2 w-full rounded border border-outline-variant/50 bg-surface-low px-3 py-2.5 text-sm font-normal outline-none focus:border-primary"><option value="">Select school</option>@foreach($schools as $school)<option value="{{ $school->id }}" @selected(old('school_id', $selectedSchoolId) == $school->id)>{{ $school->name }} ({{ $school->code }})</option>@endforeach</select></label>@else<input type="hidden" name="school_id" value="{{ $schools->first()?->id }}">@endif
        <label class="text-xs font-semibold text-on-surface-variant {{ $isMasterUser ? '' : 'md:col-span-2' }}">Purpose / Expense Type <span class="text-error">*</span><input name="purpose" required value="{{ old('purpose') }}" placeholder="e.g. Utility, travel, training, repairs" class="mt-2 w-full rounded border border-outline-variant/50 bg-surface-low px-3 py-2.5 text-sm font-normal outline-none focus:border-primary"></label>
        <label class="text-xs font-semibold text-on-surface-variant">Amount <span class="text-error">*</span><input type="number" step="0.01" min="0" name="amount" required value="{{ old('amount') }}" placeholder="0.00" class="mt-2 w-full rounded border border-outline-variant/50 bg-surface-low px-3 py-2.5 text-sm font-normal outline-none focus:border-primary"></label>
        <label class="text-xs font-semibold text-on-surface-variant md:col-span-2">Optional Linked Procurement Request<select name="procurement_request_id" class="mt-2 w-full rounded border border-outline-variant/50 bg-surface-low px-3 py-2.5 text-sm font-normal outline-none focus:border-primary"><option value="">No PR / direct expense</option>@foreach($availableProcurements as $request)<option value="{{ $request->id }}" @selected(old('procurement_request_id') == $request->id)>{{ $request->request_number }} · {{ $request->school?->name }} · {{ $request->title }}</option>@endforeach</select></label>
        <label class="text-xs font-semibold text-on-surface-variant md:col-span-2">Notes<textarea name="notes" rows="3" placeholder="Receipt numbers, billing month, supporting document notes..." class="mt-2 w-full rounded border border-outline-variant/50 bg-surface-low px-3 py-2.5 text-sm font-normal outline-none focus:border-primary">{{ old('notes') }}</textarea></label>
        <div class="flex justify-end gap-2 border-t border-outline-variant/30 pt-4 md:col-span-2"><button type="button" data-close-liquidation-modal class="rounded border border-outline-variant/60 px-4 py-2.5 text-xs font-semibold hover:bg-primary hover:text-white">Cancel</button><button type="submit" class="rounded bg-primary px-4 py-2.5 text-xs font-semibold text-white hover:bg-primary-container">Submit ORS Entry</button></div>
    </form>
</div></div>
@include('partials.profile-menu')
<script>
    const liquidationModal = document.getElementById('liquidation-modal');
    const openLiquidationModal = () => { liquidationModal?.classList.remove('hidden'); liquidationModal?.classList.add('flex'); };
    const closeLiquidationModal = () => { liquidationModal?.classList.add('hidden'); liquidationModal?.classList.remove('flex'); };
    document.getElementById('open-liquidation-modal')?.addEventListener('click', openLiquidationModal);
    document.querySelectorAll('[data-close-liquidation-modal]').forEach((button) => button.addEventListener('click', closeLiquidationModal));
    liquidationModal?.addEventListener('click', (event) => { if (event.target === liquidationModal) closeLiquidationModal(); });
    @if($errors->any()) openLiquidationModal(); @endif
</script>
</body>
</html>
