@extends('layouts.procurement')
@section('title','Procurement Overview') @section('page-title','Overview')
@section('header-actions')<a href="{{ route('procurement.create') }}" class="inline-flex min-h-10 items-center gap-2 rounded-lg bg-primary px-4 text-xs font-bold text-white"><span class="material-symbols-outlined text-[18px]">add</span><span>Create Purchase Request</span></a>@endsection
@section('content')
@php($schoolFilterParameters = $isMasterUser && request()->filled('school_id') ? ['school_id' => request('school_id')] : [])
<header class="mb-6"><p class="text-[11px] font-bold uppercase tracking-[.14em] text-action">Civic Operations</p><h1 class="mt-2 text-3xl font-bold tracking-tight">Procurement overview</h1><p class="mt-2 text-sm text-on-surface-variant">{{ $isMasterUser ? 'Monitor work across connected schools.' : 'Work requiring attention for '.$currentSchoolName.'.' }}</p></header>
<section class="mb-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4" aria-label="Procurement metrics"><x-procurement.metric-card label="Total requests" :value="$procurementMetrics['total']" note="Visible portfolio" icon="description" :href="route('procurement.requests', $schoolFilterParameters)"/><x-procurement.metric-card label="Pending approval" :value="$procurementMetrics['pending']" note="Needs review" icon="pending_actions" tone="attention" :href="route('procurement.requests', [...$schoolFilterParameters, 'status' => 'pending_approval'])"/><x-procurement.metric-card label="For canvass" :value="$procurementMetrics['forCanvass']" note="Quotation work" icon="request_quote" :href="route('procurement.requests', [...$schoolFilterParameters, 'status' => 'for_canvass'])"/><x-procurement.metric-card label="Completed" :value="$procurementMetrics['completed']" note="₱{{ number_format((float)$procurementMetrics['completedAmount'],2) }} value" icon="task_alt" tone="verified" :href="route('procurement.requests', [...$schoolFilterParameters, 'status' => 'completed'])"/></section>
<div class="grid gap-5 xl:grid-cols-[1.45fr_.75fr]"><section class="overflow-hidden rounded-xl border border-outline-variant/60 bg-white"><div class="flex items-center justify-between border-b border-outline-variant/50 px-5 py-4"><div><h2 class="font-bold">Requests needing attention</h2><p class="mt-1 text-xs text-on-surface-variant">Prioritized workflow work.</p></div><a href="{{ route('procurement.requests', $schoolFilterParameters) }}" class="text-xs font-bold text-action">View all</a></div>@forelse($attentionRequests as $request)<div class="flex min-h-16 flex-wrap items-center gap-3 border-b border-outline-variant/30 px-5 py-3 last:border-0 hover:bg-surface-low"><a href="{{ route('procurement.show',$request) }}" class="flex min-w-0 flex-1 items-center gap-3"><span class="grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-attention/10 text-attention"><span class="material-symbols-outlined">priority_high</span></span><span class="min-w-0 flex-1"><strong class="block truncate text-sm">{{ $request->title }}</strong><small class="text-on-surface-variant">{{ $request->request_number }} · {{ $request->school?->name }}</small></span></a><x-procurement.status-badge :label="$request->ready_to_complete ? 'Ready to mark complete' : $request->workflow['stage_label'].' · '.$request->workflow['steps_done'].' of '.$request->workflow['steps_total']" tone="attention"/>@if($request->ready_to_complete && auth()->user()->hasPermission('procurement.edit'))<form method="POST" action="{{ route('procurement.status', $request) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="completed"><button class="min-h-9 rounded-lg bg-secondary px-3 text-xs font-bold text-white">Mark complete</button></form>@endif</div>@empty<x-procurement.empty-state title="No urgent procurement work" description="Requests requiring follow-up appear here." icon="task_alt"/>@endforelse</section>@include('partials.procurement.task-queue')</div>
<section class="mt-5 rounded-xl border border-outline-variant/60 bg-white p-5"><h2 class="font-bold">Recent activity</h2><p class="mt-1 text-xs text-on-surface-variant">Latest visible requests.</p><div class="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">@forelse($recentRequests as $request)<a href="{{ route('procurement.show',$request) }}" class="rounded-lg border border-outline-variant/50 p-4 hover:border-action"><div class="flex justify-between gap-2"><strong class="text-primary">{{ $request->request_number }}</strong><x-procurement.status-badge :label="$request->ready_to_complete ? 'Ready to mark complete' : $request->workflow['stage_label'].' · '.$request->workflow['steps_done'].' of '.$request->workflow['steps_total']" :tone="$request->workflow['stage']==='complete'?'verified':'action'"/></div><p class="mt-3 truncate text-sm font-semibold">{{ $request->title }}</p><p class="mt-1 text-xs text-on-surface-variant">{{ $request->school?->name }} · ₱{{ number_format((float)$request->amount,2) }}</p></a>@empty<p class="text-sm text-on-surface-variant">No recent procurement activity.</p>@endforelse</div></section>
@endsection
