<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Reports · ProcureMS</title>
    <script src="https://cdn.tailwindcss.com"></script>
    <script>tailwind.config={theme:{extend:{colors:{surface:'#faf8ff','surface-low':'#f4f3fa','surface-container':'#eeedf4','surface-high':'#e9e7ef',primary:'#00236f','primary-container':'#1e3a8a','on-surface':'#1a1b21','on-surface-variant':'#444651',secondary:'#006c4a','outline-variant':'#c5c5d3',error:'#ba1a1a'},fontFamily:{inter:['Inter','sans-serif']}}}};</script>
    <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,400,0,0" rel="stylesheet"><link rel="stylesheet" href="{{ asset('css/app.css') }}">
</head>
<body class="bg-surface font-inter text-on-surface antialiased">
    <aside class="fixed inset-y-0 left-0 z-50 hidden w-72 flex-col bg-primary px-4 py-6 text-white md:flex"><div class="mb-8 flex items-center gap-3 px-2"><div class="flex h-8 w-8 items-center justify-center rounded bg-secondary"><span class="material-symbols-outlined text-[20px]">school</span></div><span class="text-xl font-semibold">ProcureMS</span></div><nav class="flex-1 space-y-1" aria-label="Main navigation">
        @php $navigation=[['icon'=>'dashboard','label'=>'Dashboard','route'=>'home'],['icon'=>'shopping_cart','label'=>'Procurement','route'=>'procurement'],['icon'=>'receipt_long','label'=>'Liquidation','route'=>'liquidation'],['icon'=>'folder','label'=>'Google Drive','route'=>'google-drive'],['icon'=>'bar_chart','label'=>'Reports','route'=>'reports','active'=>true],['icon'=>'group','label'=>'User Management'],['icon'=>'card_membership','label'=>'Subscriptions'],['icon'=>'settings','label'=>'School Settings']]; @endphp
        @foreach($navigation as $item)<a href="{{ isset($item['route']) ? route($item['route']) : ($item['label'] === 'User Management' ? route('user-management') : ($item['label'] === 'Subscriptions' ? route('subscriptions') : ($item['label'] === 'School Settings' ? route('school-settings') : '#'))) }}" class="flex items-center rounded px-3 py-2.5 text-sm {{ ($item['active'] ?? false) ? 'bg-primary-container font-semibold text-white' : 'text-white/80 hover:bg-primary-container hover:text-white' }}"><span class="material-symbols-outlined mr-3 text-[20px]">{{ $item['icon'] }}</span>{{ $item['label'] }}</a>@endforeach
    </nav><div class="border-t border-white/15 pt-4 text-xs text-white/60"><p>Multi-School Procurement System</p><p class="mt-1">v1.0 · All systems operational</p></div></aside>

    <div class="md:pl-72"><header class="fixed left-0 right-0 top-0 z-40 flex h-16 items-center justify-between border-b border-outline-variant/30 bg-surface/95 px-4 backdrop-blur md:left-72 md:px-6"><div class="flex items-center gap-3"><button class="rounded p-2 text-on-surface-variant md:hidden" aria-label="Open navigation"><span class="material-symbols-outlined">menu</span></button><span class="text-sm font-semibold text-on-surface-variant">Reports &amp; Analytics</span></div><div class="flex items-center gap-4"><button class="relative rounded p-1 text-on-surface-variant" aria-label="Notifications"><span class="material-symbols-outlined text-[21px]">notifications</span><span class="absolute right-0 top-0 h-2 w-2 rounded-full bg-error"></span></button><div class="flex h-8 w-8 items-center justify-center rounded-full bg-primary text-white"><span class="material-symbols-outlined text-[18px]">person</span></div></div></header>

    <main class="min-h-screen bg-surface px-4 pb-16 pt-24 md:px-6 lg:px-8"><div class="mx-auto max-w-[1600px]">
        <div class="mb-8 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div class="mb-2 flex items-center gap-2 text-xs font-medium uppercase tracking-wider text-on-surface-variant"><span class="material-symbols-outlined text-[16px]">bar_chart</span><span class="font-semibold text-primary">Management Intelligence</span></div><h1 class="text-[28px] font-semibold leading-9 tracking-tight">Reports &amp; Analytics</h1><p class="mt-1 text-[15px] leading-6 text-on-surface-variant">Monitor procurement activity, liquidation performance, and organization-wide spending.</p></div><div class="flex gap-2"><select class="rounded border border-outline-variant/50 bg-white px-3 py-2.5 text-xs outline-none"><option>October 2025</option><option>September 2025</option><option>Q3 2025</option></select><button class="flex items-center gap-2 rounded bg-primary px-4 py-2.5 text-xs font-semibold text-white hover:bg-primary-container"><span class="material-symbols-outlined text-[18px]">download</span>Export Report</button></div></div>

        @php $metrics=[['label'=>'Total Procurement','value'=>'₱4.82M','note'=>'+14.8% vs last period','icon'=>'shopping_cart','tone'=>'primary'],['label'=>'Total Liquidated','value'=>'₱3.96M','note'=>'82.2% of procurement','icon'=>'receipt_long','tone'=>'secondary'],['label'=>'Outstanding Balance','value'=>'₱860K','note'=>'Across 14 reports','icon'=>'pending_actions','tone'=>'error'],['label'=>'Average Processing','value'=>'4.2 days','note'=>'-0.8 days improved','icon'=>'speed','tone'=>'primary']]; @endphp
        <div class="mb-8 grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($metrics as $metric)<article class="flex items-center justify-between rounded border border-outline-variant/30 bg-white p-5"><div><p class="text-xs font-semibold uppercase tracking-wider text-on-surface-variant">{{ $metric['label'] }}</p><p class="mt-3 text-2xl font-semibold tabular-nums {{ $metric['tone']==='error' ? 'text-error' : '' }}">{{ $metric['value'] }}</p><p class="mt-1 text-xs font-medium text-{{ $metric['tone'] }}">{{ $metric['note'] }}</p></div><span class="flex h-10 w-10 items-center justify-center rounded bg-{{ $metric['tone'] }}/10 text-{{ $metric['tone'] }}"><span class="material-symbols-outlined">{{ $metric['icon'] }}</span></span></article>@endforeach</div>

        <div class="grid grid-cols-1 gap-4 xl:grid-cols-3"><section class="rounded border border-outline-variant/30 bg-white p-5 xl:col-span-2"><div class="mb-6 flex items-center justify-between"><div><h2 class="text-lg font-semibold">Monthly Spending Overview</h2><p class="mt-1 text-xs text-on-surface-variant">Procurement value compared with liquidated expenses.</p></div><span class="rounded bg-surface-low px-2 py-1 text-xs text-on-surface-variant">2025</span></div><div class="flex h-64 items-end gap-3 border-b border-l border-outline-variant/30 px-3 pb-0 pt-4 sm:gap-5"><div class="flex h-full flex-1 flex-col justify-end gap-1"><div class="flex h-[62%] items-end gap-1"><div class="w-1/2 rounded-t bg-primary" style="height:78%"></div><div class="w-1/2 rounded-t bg-secondary" style="height:54%"></div></div><span class="pt-2 text-center text-[10px] text-on-surface-variant">May</span></div><div class="flex h-full flex-1 flex-col justify-end gap-1"><div class="flex h-full items-end gap-1"><div class="w-1/2 rounded-t bg-primary" style="height:68%"></div><div class="w-1/2 rounded-t bg-secondary" style="height:49%"></div></div><span class="pt-2 text-center text-[10px] text-on-surface-variant">Jun</span></div><div class="flex h-full flex-1 flex-col justify-end gap-1"><div class="flex h-full items-end gap-1"><div class="w-1/2 rounded-t bg-primary" style="height:84%"></div><div class="w-1/2 rounded-t bg-secondary" style="height:62%"></div></div><span class="pt-2 text-center text-[10px] text-on-surface-variant">Jul</span></div><div class="flex h-full flex-1 flex-col justify-end gap-1"><div class="flex h-full items-end gap-1"><div class="w-1/2 rounded-t bg-primary" style="height:73%"></div><div class="w-1/2 rounded-t bg-secondary" style="height:68%"></div></div><span class="pt-2 text-center text-[10px] text-on-surface-variant">Aug</span></div><div class="flex h-full flex-1 flex-col justify-end gap-1"><div class="flex h-full items-end gap-1"><div class="w-1/2 rounded-t bg-primary" style="height:91%"></div><div class="w-1/2 rounded-t bg-secondary" style="height:72%"></div></div><span class="pt-2 text-center text-[10px] text-on-surface-variant">Sep</span></div><div class="flex h-full flex-1 flex-col justify-end gap-1"><div class="flex h-full items-end gap-1"><div class="w-1/2 rounded-t bg-primary" style="height:76%"></div><div class="w-1/2 rounded-t bg-secondary" style="height:59%"></div></div><span class="pt-2 text-center text-[10px] text-on-surface-variant">Oct</span></div></div><div class="mt-4 flex justify-center gap-5 text-xs text-on-surface-variant"><span class="flex items-center gap-2"><span class="h-2 w-2 rounded-full bg-primary"></span>Procurement</span><span class="flex items-center gap-2"><span class="h-2 w-2 rounded-full bg-secondary"></span>Liquidated</span></div></section>

        <section class="rounded border border-outline-variant/30 bg-white p-5"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-lg font-semibold">Spending by School</h2><p class="mt-1 text-xs text-on-surface-variant">Top institutions by total value.</p></div><span class="material-symbols-outlined text-on-surface-variant">leaderboard</span></div>@php $schools=[['name'=>'Riverbend Hills University','amount'=>'₱1.24M','width'=>'92%'],['name'=>'St. Vincent Academy','amount'=>'₱980K','width'=>'74%'],['name'=>'Global High Institute','amount'=>'₱742K','width'=>'58%'],['name'=>'Oakridge Arts & Sciences','amount'=>'₱615K','width'=>'48%'],['name'=>'Metro Polytechnic College','amount'=>'₱389K','width'=>'31%']]; @endphp<div class="space-y-4">@foreach($schools as $school)<div><div class="mb-1 flex justify-between gap-2 text-xs"><span class="truncate text-on-surface-variant">{{ $school['name'] }}</span><span class="font-semibold tabular-nums">{{ $school['amount'] }}</span></div><div class="h-2 rounded-full bg-surface-container"><div class="h-full rounded-full bg-primary" style="width:{{ $school['width'] }}"></div></div></div>@endforeach</div></section></div>

        <section class="mt-4 overflow-hidden rounded border border-outline-variant/30 bg-white"><div class="flex flex-col justify-between gap-3 border-b border-outline-variant/30 p-5 sm:flex-row sm:items-center"><div><h2 class="text-lg font-semibold">Available Reports</h2><p class="mt-1 text-xs text-on-surface-variant">Generate and download standard management reports.</p></div><div class="flex gap-2"><select class="rounded border border-outline-variant/50 bg-surface-low px-3 py-2 text-xs outline-none"><option>All Categories</option><option>Financial</option><option>Procurement</option><option>Compliance</option></select><button class="flex items-center gap-2 rounded bg-surface-high px-3 py-2 text-xs font-semibold hover:bg-surface-highest"><span class="material-symbols-outlined text-[17px]">add</span>Custom Report</button></div></div><div class="grid grid-cols-1 divide-y divide-outline-variant/20 md:grid-cols-2 md:divide-x md:divide-y-0">@php $reports=[['icon'=>'account_balance_wallet','title'=>'Procurement Expenditure Report','description'=>'Summary of approved purchases and total spending by school.','category'=>'Financial'],['icon'=>'fact_check','title'=>'Liquidation Compliance Report','description'=>'Review submission status, missing documents, and approval history.','category'=>'Compliance'],['icon'=>'inventory_2','title'=>'Supplier Performance Report','description'=>'Compare supplier awards, delivery performance, and purchase volume.','category'=>'Procurement'],['icon'=>'school','title'=>'School Activity Report','description'=>'Cross-school overview of requests, liquidations, and active users.','category'=>'Management']]; @endphp @foreach($reports as $report)<div class="flex items-center justify-between gap-4 p-5"><div class="flex min-w-0 items-start gap-3"><span class="material-symbols-outlined text-2xl text-primary">{{ $report['icon'] }}</span><div class="min-w-0"><h3 class="text-sm font-semibold">{{ $report['title'] }}</h3><p class="mt-1 text-xs leading-5 text-on-surface-variant">{{ $report['description'] }}</p><span class="mt-2 inline-flex rounded bg-surface-low px-2 py-1 text-[10px] font-semibold uppercase tracking-wider text-on-surface-variant">{{ $report['category'] }}</span></div></div><button class="shrink-0 rounded p-2 text-on-surface-variant hover:bg-surface-high hover:text-primary" title="Download report"><span class="material-symbols-outlined">download</span></button></div>@endforeach</div></section>

        <div class="mt-4 rounded border border-outline-variant/30 bg-white p-5"><div class="mb-4 flex items-center justify-between"><div><h2 class="text-lg font-semibold">Recent Exports</h2><p class="mt-1 text-xs text-on-surface-variant">Previously generated reports available for download.</p></div><button class="text-xs font-semibold text-primary hover:underline">View export history</button></div><div class="grid grid-cols-1 gap-3 md:grid-cols-3"><div class="flex items-center gap-3 rounded bg-surface-low p-3"><span class="material-symbols-outlined text-error">picture_as_pdf</span><div class="min-w-0 flex-1"><p class="truncate text-xs font-semibold">Q3 Liquidation Compliance.pdf</p><p class="mt-1 text-[10px] text-on-surface-variant">Generated yesterday · 2.4 MB</p></div><span class="material-symbols-outlined text-sm text-primary">download</span></div><div class="flex items-center gap-3 rounded bg-surface-low p-3"><span class="material-symbols-outlined text-secondary">table_view</span><div class="min-w-0 flex-1"><p class="truncate text-xs font-semibold">September Procurement.xlsx</p><p class="mt-1 text-[10px] text-on-surface-variant">Generated Sep 30 · 840 KB</p></div><span class="material-symbols-outlined text-sm text-primary">download</span></div><div class="flex items-center gap-3 rounded bg-surface-low p-3"><span class="material-symbols-outlined text-error">picture_as_pdf</span><div class="min-w-0 flex-1"><p class="truncate text-xs font-semibold">School Activity Summary.pdf</p><p class="mt-1 text-[10px] text-on-surface-variant">Generated Sep 28 · 1.1 MB</p></div><span class="material-symbols-outlined text-sm text-primary">download</span></div></div></div>
    </div></main></div>
</body>
</html>
