@php
    $items=$procurementRequest->items; $staffById=$iarsStaff->keyBy('id');
    $assignments=collect(($document->metadata ?? [])['iars_assignments'] ?? [])->filter(fn($row)=>!empty($row['staff_id']))->values();
    $staffRows=$assignments->map(fn($row)=>['staff'=>$staffById->get($row['staff_id']), 'items'=>$row['items'] ?? []]);
    $receivedItems = ($inspectionAcceptanceReport?->metadata ?? [])['received_items'] ?? [];
    $actualReceivedQuantity = fn($item) => ($receivedItems[$item->id] ?? null) === null || ($receivedItems[$item->id] ?? '') === ''
        ? (float) $item->quantity
        : (float) $receivedItems[$item->id];
    $transactionDescription = $procurementRequest->transaction_description
        ?: data_get($document->metadata, 'transaction_description')
        ?: data_get($purchaseOrder?->metadata ?? [], 'transaction_description');
    $projectTitle = data_get($document->metadata, 'project_title')
        ?: data_get($purchaseOrder?->metadata ?? [], 'project_title')
        ?: $procurementRequest->title;
    $purposeText = collect([$transactionDescription, $projectTitle])->filter()->implode(' for ');
@endphp
<style>.iars-page{width:297mm;min-height:210mm;padding:12mm 14mm;font-family:Arial,sans-serif;font-size:8.5pt}.iars-title{text-align:center;font-size:11pt;font-weight:700}.iars-page-no{float:right;margin-top:-5mm}.iars-intro{margin:7mm 0 5mm;font-size:9pt;line-height:1.45}.iars-table{width:100%;border-collapse:collapse;table-layout:fixed}.iars-table td,.iars-table th{border:1px solid #111;padding:3px 4px;vertical-align:middle}.iars-table th{text-align:center;font-weight:700}.iars-table .staff{width:19%;padding-left:4px}.iars-table .signature{width:16%}.iars-table .item-head{height:24mm;font-family:"Times New Roman",serif;font-size:8.5pt;line-height:1.2}.iars-table .staff-row td{height:11mm}.iars-table .center{text-align:center}.iars-table .total{font-weight:700}.iars-table .total td,.iars-table tbody tr:last-child td{height:6mm}.iars-prepared{margin-top:6mm;font-size:9pt}.iars-sign{margin:10mm 0 0 18mm;text-align:center;width:42mm;font-size:8.5pt}.iars-sign strong{text-decoration:underline}@media print{@page{size:A4 landscape;margin:0}.iars-page{margin:0;width:297mm;min-height:210mm;box-shadow:none}}</style>
<main class="page iars-page"><div class="iars-page-no">Page 1 of 1</div><div class="iars-title">INVENTORY AND ACKNOWLEDGEMENT RECEIPT OF SUPPLIES</div><p><strong>TO WHOM IT MAY CONCERN:</strong></p><p class="iars-intro">We, the undersigned staffs of the school, hereby acknowledged the {{ $purposeText }} of {{ strtoupper($procurementRequest->school?->name) }}.</p><table class="iars-table"><colgroup><col class="staff">@foreach($items as $item)<col>@endforeach<col class="signature"></colgroup><thead><tr><th>NAME OF STAFF</th>@foreach($items as $item)<th class="item-head">{{ $item->name }}</th>@endforeach<th>SIGNATURE</th></tr></thead><tbody>@foreach($staffRows as $row)<tr class="staff-row"><td>{{ strtoupper($row['staff']?->name ?? '') }}</td>@foreach($items as $item)<td class="center">{{ ($row['items'][$item->id] ?? '') }}</td>@endforeach<td></td></tr>@endforeach<tr class="total"><td>TOTAL</td>@foreach($items as $item)@php $issued=$staffRows->sum(fn($row)=>(float)($row['items'][$item->id] ?? 0)); @endphp<td class="center">{{ number_format($issued,0) }}</td>@endforeach<td></td></tr><tr><td>Ending Balance</td>@foreach($items as $item)@php $issued=$staffRows->sum(fn($row)=>(float)($row['items'][$item->id] ?? 0)); @endphp<td class="center">{{ number_format($actualReceivedQuantity($item)-$issued,0) }}</td>@endforeach<td></td></tr></tbody></table><div class="iars-prepared">Prepared by:</div><div class="iars-sign"><strong>{{ strtoupper($schoolHead?->name ?? $procurementRequest->school?->school_head ?? '') }}</strong><br>School Head</div></main>
