@php
    $meta = $document->metadata ?? [];
    $isIar = $document->document_type === 'inspection_acceptance_report';
    $linkedPrices = $meta['awarded_item_prices'] ?? [];
    $linkedAmount = (float) ($meta['winning_bid_amount'] ?? $procurementRequest->amount);
@endphp
<style>.generic-page{width:210mm;min-height:297mm;padding:12mm;font-size:11px}@media print{.generic-page{box-shadow:none}}</style>
<main class="page generic-page">
    @include('procurement-documents._header')
    <h1 class="center upper" style="font-size:18px;margin:20px 0 14px">{{ $documentDefinition['label'] }}</h1>
    <table class="doc-table" style="margin-bottom:12px"><tr><td class="bold" style="width:18%">Document No.</td><td>{{ $document->document_number }}</td><td class="bold" style="width:18%">Date</td><td>{{ $document->document_date->format('F d, Y') }}</td></tr><tr><td class="bold">PR No.</td><td>{{ $procurementRequest->request_number }}</td><td class="bold">PR Date</td><td>{{ optional($procurementRequest->requested_at ?? $procurementRequest->created_at)->format('F d, Y') }}</td></tr>@if($isIar)<tr><td class="bold">PO No.</td><td>{{ $meta['purchase_order_number'] ?? '—' }}</td><td class="bold">PO Date</td><td>{{ $meta['purchase_order_date'] ?? '—' }}</td></tr>@endif<tr><td class="bold">Supplier / Recipient</td><td colspan="3">{{ $document->supplier_or_recipient ?: '—' }}</td></tr><tr><td class="bold">Purpose</td><td colspan="3">{{ $procurementRequest->title }}</td></tr></table>
    <table class="doc-table"><thead><tr><th style="width:7%">No.</th><th style="width:12%">Unit</th><th>Item Description</th><th style="width:12%">{{ $isIar ? 'Delivered Qty.' : 'Quantity' }}</th><th style="width:16%">Unit Cost</th><th style="width:17%">Total Cost</th></tr></thead><tbody>@foreach($procurementRequest->items as $item)@php $unitCost = $isIar && is_numeric(data_get($linkedPrices, $item->id)) ? (float) data_get($linkedPrices, $item->id) : (float) $item->unit_price; $lineTotal = $unitCost * (float) $item->quantity; @endphp<tr><td class="center">{{ $loop->iteration }}</td><td class="center">{{ strtoupper($item->unit) }}</td><td>{{ $item->name }}@if($item->description)<br><small>{{ $item->description }}</small>@endif</td><td class="money">{{ number_format((float)$item->quantity, 2) }}</td><td class="money">{{ number_format($unitCost, 2) }}</td><td class="money">{{ number_format($lineTotal, 2) }}</td></tr>@endforeach<tr><td colspan="5" class="right bold">TOTAL</td><td class="money bold">₱{{ number_format($isIar ? $linkedAmount : (float) $procurementRequest->amount, 2) }}</td></tr></tbody></table>
    <div style="display:grid;grid-template-columns:1fr 1fr;gap:35px;margin-top:55px;text-align:center"><div><div style="border-top:1px solid #111;padding-top:5px" class="bold">{{ $requestingOfficer?->name ?? $procurementOfficer?->name ?? $document->creator?->name ?? $procurementRequest->requester?->name }}</div><small>{{ $requestingOfficer?->position ?? $procurementOfficer?->position ?? 'Prepared by' }}</small></div><div><div style="border-top:1px solid #111;padding-top:5px" class="bold">{{ $approver?->name ?? $schoolHead?->name ?? '' }}</div><small>{{ $approver?->position ?? $schoolHead?->position ?? 'Approved / Received by' }}</small></div></div>
</main>
